# Generated by Django 5.2.17 on 2026-09-03 09:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('default_branch', models.CharField(blank=True, max_length=100)),
                ('billing_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_no', models.CharField(max_length=25, unique=True)),
                ('vehicle_type', models.CharField(max_length=80)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_code', models.CharField(max_length=30, unique=True)),
                ('legal_name', models.CharField(max_length=180)),
                ('display_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'On hold'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_name', models.CharField(blank=True, max_length=120)),
                ('primary_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('tax_identifier', models.CharField(blank=True, max_length=30)),
                ('default_tds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('default_tds_policy', models.CharField(blank=True, choices=[('PER_PAYMENT_TAXABLE_AMOUNT', 'Per payment taxable amount'), ('FULL_FREIGHT_AT_FIRST_ADVANCE', 'Full freight at first advance'), ('CUMULATIVE_TRIP_LIABILITY', 'Cumulative trip liability'), ('MANUAL_WITH_APPROVAL', 'Manual with approval')], max_length=40)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('blocked_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('POD', 'POD'), ('LR', 'LR'), ('VENDOR_INVOICE', 'Vendor invoice'), ('PAYMENT_PROOF', 'Payment proof'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indent_no', models.CharField(max_length=50, unique=True)),
                ('indent_date', models.DateField()),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('reporting_datetime', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('uom_ltrs', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('total_load', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('required_vehicle_type', models.CharField(blank=True, max_length=80)),
                ('customer_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indents', to='operations.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('deployment_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('uom_ltrs', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('total_load', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('vehicle_registration_snapshot', models.CharField(max_length=25)),
                ('vehicle_type_snapshot', models.CharField(max_length=80)),
                ('driver_name_snapshot', models.CharField(max_length=120)),
                ('driver_phone_snapshot', models.CharField(max_length=30)),
                ('vendor_freight_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('advance_percent', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5)),
                ('client_billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ADVANCE_APPROVAL_PENDING', 'Advance approval pending'), ('ADVANCE_APPROVED', 'Advance approved'), ('ADVANCE_PARTIALLY_PAID', 'Advance partially paid'), ('ADVANCE_PAID', 'Advance paid'), ('DEPLOYED', 'Deployed'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('SETTLEMENT_PENDING', 'Settlement pending'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('CANCELLED_WITH_PAYMENT', 'Cancelled with payment')], db_index=True, default='READY', max_length=35)),
                ('pod_status', models.CharField(default='PENDING', max_length=30)),
                ('settlement_status', models.CharField(default='OPEN', max_length=30)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.driver')),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.indent')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.vehicle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='TripCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('FREIGHT', 'Freight'), ('UNLOADING', 'Unloading'), ('DETENTION', 'Detention'), ('LOADING', 'Loading'), ('TOLL', 'Toll'), ('OTHER', 'Other'), ('DEDUCTION', 'Deduction'), ('REIMBURSEMENT', 'Reimbursement')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('direction', models.CharField(choices=[('ADD', 'Add'), ('DEDUCT', 'Deduct')], default='ADD', max_length=10)),
                ('advance_eligible', models.BooleanField(default=False)),
                ('tds_eligible', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('INITIAL', 'Initial'), ('FINAL_SETTLEMENT', 'Final settlement'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], default='INITIAL', max_length=25)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='operations.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='operations.vendor'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='operations.vendor'),
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_holder', models.CharField(max_length=150)),
                ('account_number_encrypted', models.TextField()),
                ('account_last_four', models.CharField(max_length=4)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='operations.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('receives_email', models.BooleanField(default=True)),
                ('receives_whatsapp', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='operations.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['deployment_date', 'status'], name='operations__deploym_9d95c4_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vendor', 'deployment_date'], name='operations__vendor__9b93c6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle_registration_snapshot'], name='operations__vehicle_257365_idx'),
        ),
    ]
