# Generated by Django 5.2.17 on 2026-09-03 10:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scan_detail',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ADVANCE_APPROVAL_PENDING', 'Advance approval pending'), ('ADVANCE_APPROVED', 'Advance approved'), ('ADVANCE_PARTIALLY_PAID', 'Advance partially paid'), ('ADVANCE_PAID', 'Advance paid'), ('DEPLOYED', 'Deployed'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('SETTLEMENT_PENDING', 'Settlement pending'), ('SETTLEMENT_APPROVAL_PENDING', 'Settlement approval pending'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('CANCELLED_WITH_PAYMENT', 'Cancelled with payment')], db_index=True, default='READY', max_length=35),
        ),
        migrations.CreateModel(
            name='TripRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('resolution_method', models.CharField(choices=[('REFUND', 'Refund'), ('ADJUST_AGAINST_FUTURE_TRIP', 'Adjust against future trip'), ('WRITE_OFF_WITH_APPROVAL', 'Write off with approval'), ('OTHER', 'Other')], max_length=40)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recoveries', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_recoveries', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recovery', to='operations.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
