# Generated by Django 5.2.17 on 2026-09-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(default='ADVANCE', max_length=30)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentApprovalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CHANGES_REQUESTED', 'Changes requested'), ('PARTIALLY_APPROVED', 'Partially approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=30)),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('approval_rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('gross_requested', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tds_requested', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_requested', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('purpose', models.CharField(default='ADVANCE', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_batches', to='operations.client')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentApprovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freight_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('advance_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('freight_advance_gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('advance_eligible_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('advance_stage_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tds_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds_policy_snapshot', models.CharField(choices=[('PER_PAYMENT_TAXABLE_AMOUNT', 'Per payment taxable amount'), ('FULL_FREIGHT_AT_FIRST_ADVANCE', 'Full freight at first advance'), ('CUMULATIVE_TRIP_LIABILITY', 'Cumulative trip liability'), ('MANUAL_WITH_APPROVAL', 'Manual with approval')], max_length=40)),
                ('tds_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tds_this_request', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('calculation_breakdown', models.JSONField(default=dict)),
                ('item_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=30)),
                ('approver_note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='approvals.paymentapprovalbatch')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_items', to='operations.trip')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_items', to='operations.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SEND_BACK', 'Send back'), ('CANCEL', 'Cancel'), ('REOPEN', 'Reopen')], max_length=20)),
                ('scope', models.CharField(choices=[('BATCH', 'Batch'), ('ITEM', 'Item')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('approval_stage', models.PositiveSmallIntegerField(default=1)),
                ('captured_totals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='approvals.paymentapprovalbatch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='approvals.paymentapprovalitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('role', models.CharField(default='APPROVER', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approvals.approvalrule')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'sequence'), name='unique_rule_stage_sequence')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('TRANSPORTER_VISIBLE', 'Transporter visible')], default='INTERNAL', max_length=30)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='approvals.comment')),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'object_id', 'created_at'], name='approvals_c_object__b58673_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentapprovalitem',
            index=models.Index(fields=['vendor', 'item_status'], name='approvals_p_vendor__edf39f_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentapprovalitem',
            constraint=models.UniqueConstraint(fields=('batch', 'trip'), name='unique_trip_per_approval_batch'),
        ),
        migrations.AddConstraint(
            model_name='paymentapprovalitem',
            constraint=models.CheckConstraint(condition=models.Q(('gross_requested__gte', 0)), name='approval_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentapprovalitem',
            constraint=models.CheckConstraint(condition=models.Q(('tds_this_request__gte', 0)), name='approval_tds_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentapprovalitem',
            constraint=models.CheckConstraint(condition=models.Q(('net_requested__gte', 0)), name='approval_net_nonnegative'),
        ),
    ]
