# Generated by Django 5.2.17 on 2026-09-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('DRAFT', 'Draft'), ('INVOICED', 'Invoiced'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received')], default='DRAFT', max_length=30)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('internal_trip_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='operations.client')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing', to='operations.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTripSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_freight', models.DecimalField(decimal_places=2, max_digits=14)),
                ('additive_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vendor_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_vendor_gross_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_tds_required', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_tds_deducted', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_net_vendor_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cash_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_cash_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settlement_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Approval pending'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled')], default='DRAFT', max_length=30)),
                ('settlement_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='approvals.paymentapprovalbatch')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_settlement', to='operations.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(default='BANK_TRANSFER', max_length=30)),
                ('utr_reference', models.CharField(db_index=True, max_length=100)),
                ('gross_allocated_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('net_paid_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.vendorbankaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_payments', to=settings.AUTH_USER_MODEL)),
                ('proof_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.document')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount_allocated', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tds_allocated', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_cash_allocated', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='approvals.paymentapprovalitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.financepaymenttransaction')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='operations.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TDSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('policy_snapshot', models.CharField(max_length=40)),
                ('deduction_date', models.DateField()),
                ('status', models.CharField(default='POSTED', max_length=20)),
                ('finance_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tds_entries', to='payments.financepaymenttransaction')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tds_entries', to='operations.trip')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tds_entries', to='operations.vendor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='financepaymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('gross_allocated_amount__gte', 0)), name='payment_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financepaymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('tds_amount__gte', 0)), name='payment_tds_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financepaymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('net_paid_amount__gte', 0)), name='payment_net_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'approval_item'), name='unique_payment_approval_allocation'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount_allocated__gte', 0)), name='allocation_gross_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('tds_allocated__gte', 0)), name='allocation_tds_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('net_cash_allocated__gte', 0)), name='allocation_net_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tdsentry',
            constraint=models.UniqueConstraint(fields=('payment', 'trip'), name='unique_payment_trip_tds_entry'),
        ),
    ]
