# Generated by Django 5.2.17 on 2026-09-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail'), ('WHATSAPP', 'WhatsApp')], max_length=20, unique=True)),
                ('status', models.CharField(default='DISCONNECTED', max_length=20)),
                ('account_label', models.CharField(blank=True, max_length=150)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('watch_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In app')], max_length=20)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=10)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('external_thread_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=80)),
                ('recipient', models.CharField(blank=True, max_length=180)),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=240)),
                ('body_summary', models.TextField(blank=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_messages', to='operations.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnmappedInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=240)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationmessage')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
