# Generated by Django 5.2.17 on 2026-09-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='payload_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In app')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=240)),
                ('body_template', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_key', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'channel'), name='unique_notification_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In app')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event_key', 'channel'), name='unique_user_event_channel')],
            },
        ),
    ]
