# Generated by Django 5.2.17 on 2026-09-03 09:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NPL Transport Operations', max_length=150)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('default_advance_percent', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('default_tds_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('default_tds_policy', models.CharField(choices=[('PER_PAYMENT_TAXABLE_AMOUNT', 'Per payment taxable amount'), ('FULL_FREIGHT_AT_FIRST_ADVANCE', 'Full freight at first advance'), ('CUMULATIVE_TRIP_LIABILITY', 'Cumulative trip liability'), ('MANUAL_WITH_APPROVAL', 'Manual with approval')], default='PER_PAYMENT_TAXABLE_AMOUNT', max_length=40)),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('require_payment_proof', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
