# Generated by Django 5.2.17 on 2026-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='audit_retention_days',
            field=models.PositiveIntegerField(default=2555),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='comment_edit_window_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='require_pod_for_settlement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='require_vendor_invoice_for_settlement',
            field=models.BooleanField(default=True),
        ),
    ]
