# Generated by Django 5.2.17 on 2026-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='original_file',
            field=models.FileField(blank=True, upload_to='imports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
